let refreshSequence=0,stockJump=null,analysisStart='',analysisEnd='',modelConfigured=false,authUser=null;
function rangeQuery(){return `?days=${days}${category?'&category='+encodeURIComponent(category):''}${location.hash==='#analytics'&&analysisStart&&analysisEnd?'&start='+analysisStart+'&end='+analysisEnd:''}`}

const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages={overview:['总览','掌握库存状态，跟进今天需要处理的需求。','▦'],planning:['需求计划','结合销售预测、现货与确认入库，形成备货需求。','◷'],requests:['补货需求单','从需求提出到生产反馈，再到成品入库。','▤'],inventory:['库存明细','查看当前库存与每一次库存变化。','▥'],sales:['销售明细','按商品、按日期核对销售记录。','▧'],analytics:['经营分析','从销售与库存两端，理解商品表现。','◴'],settings:['数据与设置','管理数据来源、生产提前期与备货规则。','⚙']};
let setupPrompted=null,pollTimer=null,refreshBusy=false;
let dataset=null, workspace=null, days=30, category='', search='', tab='current', page='overview', loaded=false;
const status={draft:'草稿',pending:'待生产确认',confirmed:'已确认',partial:'部分入库',completed:'已完成',cancelled:'已取消'};
const num=x=>x==null?'—':Number(x).toLocaleString('zh-CN',{maximumFractionDigits:2});
const badge=(t,cls='')=>`<span class="tag ${cls}">${esc(t)}</span>`;
const button=(text,action,extra='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',6000)}
async function api(url,data){const r=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let out=await r.json();if(r.status===401){showAuth('login');throw Error('请先登录')}if(!r.ok)throw Error(typeof out.detail==='string'?out.detail:JSON.stringify(out.detail));return out}
function showAuth(mode='login',message=''){document.body.className='auth-required';$('#auth-content').innerHTML=`<form id="auth-form" data-mode="${mode}"><label>邮箱</label><input name="email" type="email" autocomplete="email" required maxlength="254"><label>密码</label><input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" required minlength="8" maxlength="128">${message?`<p class="auth-error">${esc(message)}</p>`:''}<div class="form-actions"><button type="button" data-action="auth-mode" data-mode="${mode==='login'?'register':'login'}">${mode==='login'?'注册账号':'返回登录'}</button><button class="primary" type="submit">${mode==='login'?'登录':'注册并进入'}</button></div></form>`}
function showApp(me){authUser=me;document.body.className='';$('#account').innerHTML=me.auth_enabled?`<span class="account">${esc(me.email)} ${button('退出','logout')}</span>`:''}
function path(suffix=''){return `/planning/${dataset.dataset_id}${suffix}`}
let insightTimer=null;
const insightRequests=new Map();
function insightKey(){const s=workspace.statistics;return `${dataset.dataset_id}|${workspace.state.revision}|${s.start}|${s.end}|${category}`}
function matchingInsight(){const s=workspace.statistics,i=workspace.state.insight;return i&&i.analysis_version===3&&i.revision===workspace.state.revision&&i.start===s.start&&i.end===s.end&&(i.category||'')===category}
function queueInsight(){clearTimeout(insightTimer);if(!modelConfigured||page!=='analytics'||!workspace.statistics.products.length||matchingInsight())return;const key=insightKey();if(insightRequests.has(key))return;insightTimer=setTimeout(()=>runInsight(),400)}
async function runInsight(retry=false){
 if(!modelConfigured||page!=='analytics'||!dataset)return;
 const key=insightKey();if(!retry&&insightRequests.has(key))return;
 const url=path('/insight')+rangeQuery();insightRequests.set(key,{status:'running'});render();
 try{const result=await api(url,{});insightRequests.set(key,{status:'complete',result});if(dataset&&workspace&&insightKey()===key){workspace.state.insight=result;render()}}
 catch(err){insightRequests.set(key,{status:'error',message:err.message});if(dataset&&workspace&&insightKey()===key)render()}
}
function insightPanel(){
 if(!modelConfigured)return panel('AI 综合解读','<div class="panel-body">未配置模型，AI 解读暂不可用。预测与补货功能可正常使用。</div>');
 const matching=matchingInsight(),item=insightRequests.get(insightKey()),i=workspace.state.insight;
 if(matching)return panel('AI 综合解读',`<div class="panel-body"><h3>销售表现解读</h3><div class="insight">${esc(i.sales_interpretation)}</div><h3>库存情况解读</h3><div class="insight">${esc(i.inventory_interpretation)}</div><p class="note">${esc(i.start)} 至 ${esc(i.end)} · ${esc(i.category||'全部品类')}</p></div>`);
 if(item?.status==='complete'){workspace.state.insight=item.result;return insightPanel()}
 return panel('AI 综合解读',`<div class="panel-body" aria-live="polite"><div class="insight">${item?.status==='error'?esc(item.message):workspace.statistics.products.length?'正在分析当前范围内的销售与库存数据，完成后自动显示…':'当前范围没有商品数据，暂时无法分析。'}</div></div>`,item?.status==='error'?button('重试','insight','','primary'):'');
}
async function refresh(){if(!dataset)return;const seq=++refreshSequence,key=dataset.dataset_id;const next=await api(path()+rangeQuery());if(seq!==refreshSequence||key!==dataset.dataset_id)return;workspace=next;render();queueInsight();clearTimeout(pollTimer);if(workspace.state.calculation?.status==='running')pollTimer=setTimeout(()=>refresh().catch(e=>toast(e.message)),1800);if(!workspace.state.setup_complete&&setupPrompted!==dataset.dataset_id){setupPrompted=dataset.dataset_id;await setupDialog()}}
function panel(title,body,action=''){return `<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}" class="empty">暂无记录</td></tr>`}</tbody></table></div>`}
function metrics(items){return `<div class="metrics">${items.map(([a,b,c])=>`<div class="metric"><span>${a}</span><strong>${num(b)}</strong><small>${c||' '}</small></div>`).join('')}</div>`}
function empty(){return `<div class="panel empty"><span style="font-size:36px">▥</span><strong>从一份销售与库存数据开始</strong><p>① 导入数据或加载示例　→　② 确认备货参数</p>${button('导入数据','import','','primary')}${button('加载示例数据','sample')}<p class="note">示例商品名称来自公开零售目录；销量、库存为合成数据。</p></div>`}
function filtered(){return workspace.statistics.products.filter(p=>(p.name+p.sku).toLowerCase().includes(search.toLowerCase()))}
function productName(p){return `${esc(p.name)}<small>${esc(p.sku)}</small>`}
function attentionProducts(){return workspace.statistics.products.filter(p=>{const f=workspace.state.forecasts[p.sku];if(f?.revision===workspace.state.revision&&f.status==='ready'&&p.supply_risk)return p.supply_risk.periods.length>0||f.quantity>0;return p.missing||p.stock===0||(p.coverage!=null&&p.coverage<p.lead_days)})}
function attentionText(p){
 const f=workspace.state.forecasts[p.sku],fresh=f?.revision===workspace.state.revision&&f.status==='ready';
 if(fresh){
  const parts=[];
  if(f.quantity>0)parts.push(`建议补货 ${num(f.quantity)} 件`);
  const risk=p.after_replenishment_risk;
  if(risk?.periods.length){
   const dates=risk.periods.map(t=>t.start===t.end?t.start:`${t.start} 至 ${t.end}`).join('、');
   parts.push(`${f.quantity>0?'正常补货后，':''}预计 ${dates} 存在缺货，预计损失销售额 ${num(risk.sales_at_risk)} 元`);
  }
  return parts.join('；');
 }
 return p.missing?'销售记录缺失':p.stock===0?'当前无现货，正在更新补货建议':'正在更新补货建议';
}

function overview(){const s=workspace.state, products=workspace.statistics.products, attention=attentionProducts();const active=s.requests.filter(o=>['confirmed','partial'].includes(o.status));return metrics([['现货总量',products.reduce((n,p)=>n+p.stock,0),'数据截至日快照'],['需要关注的商品',attention.length,'缺货、覆盖不足或记录缺失'],['待生产确认',s.requests.filter(o=>o.status==='pending').length,'已提出，尚未承诺供货'],['已确认待入库',products.reduce((n,p)=>n+p.incoming,0),'不包含草稿与待确认数量']])+`<div class="grid wide">`+panel('值得关注',attention.slice(0,8).map(p=>`<div class="attention"><div>${productName(p)}<p>${esc(attentionText(p))}</p><p>现货 ${num(p.stock)} 件 · 确认待入库 ${num(p.incoming)} 件</p></div><div>${button('查看方案',p.missing?'repair':'forecast',`data-sku="${esc(p.sku)}"`,'small')}${button('库存明细','stock-jump',`data-sku="${esc(p.sku)}"`,'small')}</div></div>`).join('')||'<div class="panel-body muted">当前没有上述风险信号</div>')+panel('近期事件',s.events.filter(e=>['create','submit','feedback','receive','cancel'].includes(e.type)&&e.items?.length).slice(0,8).map(e=>`<div class="event"><span>${esc(e.text)}</span><time>${esc(e.time.replace('T',' '))}</time></div>`).join('')||'<div class="panel-body muted">确认需求或登记入库后，事件会显示在这里。</div>')+`</div>`+panel('即将入库',table(['需求单','商品','剩余数量','承诺入库日期'],active.flatMap(o=>o.lines.filter(l=>l.confirmed>l.received).map(l=>`<tr><td>${esc(o.id)}</td><td>${esc(dataset.products.find(p=>p.sku===l.sku)?.name||l.sku)}</td><td>${num(l.confirmed-l.received)}</td><td>${esc(l.confirmed_due)} ${l.confirmed_due<dataset.as_of?badge('已延期','warn'):''}</td></tr>`))),'<a href="#requests">查看全部 →</a>')}
function planning(){return `<div class="warning">生产提前期 ${workspace.state.parameters.lead_days} 天，目标服务水平 ${Math.round(workspace.state.parameters.service*100)}%。系统每天检查，并扣除能及时入库的已确认数量。</div>`+panel('商品需求计划',table(['商品','现货 / 待入库','预测结果','建议新增补货','操作'],filtered().map(p=>{const f=workspace.state.forecasts[p.sku];const pending=workspace.state.requests.find(o=>['draft','pending'].includes(o.status)&&o.lines.some(l=>l.sku===p.sku));return `<tr><td>${productName(p)}</td><td>${num(p.stock)} / ${num(p.incoming)}</td><td>${f?f.status==='ready'?`${badge('已计算')}<small>预测未来 ${f.daily.length} 天</small>`:badge(shortHistory(f)?'销售历史较短':'暂未生成建议','warn'):badge('尚未计算')}</td><td>${f?.status==='ready'?num(f.quantity):'—'}${pending?`<small>已有 ${esc(pending.id)} 待处理</small>`:''}</td><td>${button(f?(f.status==='ready'?'查看备货方案':'查看原因'):'等待自动计算','forecast',`data-sku="${esc(p.sku)}"`,'small')}</td></tr>`}))) }
function requests(){return panel('补货需求单',table(['需求单','商品','需求 / 确认 / 已入库','期望日期','状态','操作'],workspace.state.requests.map(o=>`<tr><td>${esc(o.id)}<small>${esc(o.created.slice(0,10))}</small></td><td>${o.lines.map(l=>esc(dataset.products.find(p=>p.sku===l.sku)?.name||l.sku)).join('<br>')}</td><td>${o.lines.map(l=>`${num(l.quantity)} / ${num(l.confirmed)} / ${num(l.received)}`).join('<br>')}</td><td>${o.lines.map(l=>esc(l.due)).join('<br>')}</td><td>${badge(status[o.status],o.status==='pending'?'warn':'')}</td><td>${button('查看详情','order',`data-id="${esc(o.id)}"`,'small')}</td></tr>`)))}
function detailRows(kind){return workspace.statistics[kind==='sales'?'sales_rows':'ledger'].filter(r=>(r.name+r.sku).includes(search))}
function exportTable(){
 if(page==='sales')return {title:'销售明细',head:['日期','SKU','商品','销量','当日售价（元）','当日入库'],rows:detailRows('sales').map(r=>[r.date,r.sku,r.name,r.units,r.price,r.received])};
 if(tab==='current')return {title:'当前库存',head:['数据截至日','SKU','商品','品类','现货','待入库','近7天销量','近30天销量'],rows:filtered().map(p=>[dataset.as_of,p.sku,p.name,p.category,p.stock,p.incoming,p.missing_7d?null:p.sales_7d,p.missing_30d?null:p.sales_30d])};
 return {title:'库存流水',head:['日期','SKU','商品','期初','入库','销售消耗','期末'],rows:detailRows('ledger').map(r=>[r.date,r.sku,r.name,r.opening,r.received,r.sales,r.closing])};
}
function csvText(head,rows){const cell=value=>{let text=String(value??'');if(typeof value==='string'&&/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"'};return '\ufeff'+[head,...rows].map(row=>row.map(cell).join(',')).join('\r\n')+'\r\n'}
function exportDetails(){const data=exportTable();if(!data.rows.length){toast('当前筛选范围没有可导出的记录');return}const url=URL.createObjectURL(new Blob([csvText(data.head,data.rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=data.title+'_'+dataset.as_of+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出 '+data.rows.length+' 条记录')}
function inventory(){const s=workspace.statistics;return `<div class="tabs">${button('当前库存','tab','data-tab="current"',tab==='current'?'active':'')}${button('库存流水','tab','data-tab="ledger"',tab==='ledger'?'active':'')}</div>`+(tab==='current'?panel('商品库存',table(['商品','品类','现货','待入库','近7天销量','近30天销量','操作'],filtered().map(p=>{const original=p;return `<tr><td>${productName(p)}</td><td>${esc(p.category)}</td><td>${num(p.stock)}</td><td>${num(p.incoming)}</td><td>${num(original?.sales_7d)}</td><td>${num(original?.sales_30d)}${original?.missing_30d?'<small>数据不全</small>':''}</td><td>${button('商品详情','product',`data-sku="${esc(p.sku)}"`,'small')}</td></tr>`}))):panel('库存流水',table(['日期','商品','期初','入库','销售消耗','期末'],detailRows('ledger').slice(0,300).map(r=>`<tr><td>${esc(r.date)}</td><td>${productName(r)}</td><td>${num(r.opening)}</td><td>${num(r.received)}</td><td>${num(r.sales)}</td><td>${num(r.closing)}</td></tr>`)))+'<p class="note">显示筛选范围最近 300 条。导出包含筛选范围内全部记录。</p>')}
function sales(){const missing=workspace.statistics.products.filter(p=>p.missing);return (missing.length?`<div class="warning">${missing.map(p=>`${esc(p.name)}：缺 ${p.missing} 天 ${button('补全','repair',`data-sku="${esc(p.sku)}"`,'small')}`).join('　')}</div>`:'')+panel('每日销售记录',table(['日期','商品','销量','当日售价（元）','当日入库'],detailRows('sales').slice(0,300).map(r=>`<tr><td>${esc(r.date)}</td><td>${productName(r)}</td><td>${num(r.units)}</td><td>${esc(r.price)}</td><td>${num(r.received)}</td></tr>`)))+'<p class="note">显示最近 300 条记录。导出包含筛选范围内全部记录。售价默认按人民币（元）统计。</p>'}
function chart(rows,fields,unit='件'){
 const values=rows.flatMap(r=>fields.map(([k])=>r[k])).filter(v=>v!=null),max=Math.max(1,...values)*1.12,min=Math.min(0,...values)*1.12,w=680,h=190,left=72,top=24;
 const x=i=>left+i*w/Math.max(1,rows.length-1),y=v=>top+(max-v)/(max-min)*h;
 const ticks=[...new Set([0,Math.floor((rows.length-1)/3),Math.floor(2*(rows.length-1)/3),rows.length-1])].filter(i=>i>=0);
 return `<svg class="chart analysis-chart" viewBox="0 0 780 260" role="img" aria-label="${esc(unit)}趋势，${esc(rows[0]?.date)}至${esc(rows.at(-1)?.date)}"><text x="${left}" y="13" fill="#63776b" font-size="11">${esc(unit)}</text>${[0,1,2,3,4].map(i=>{const v=min+(max-min)*i/4;return `<line x1="${left}" y1="${y(v)}" x2="752" y2="${y(v)}" stroke="#e5ede7" stroke-dasharray="3 4"/><text x="62" y="${y(v)+4}" text-anchor="end" fill="#728479" font-size="11">${num(Math.round(v))}</text>`}).join('')}${min<0?`<line x1="${left}" y1="${y(0)}" x2="752" y2="${y(0)}" stroke="#89978e" stroke-dasharray="6 4"/>`:''}${fields.map(([key,color])=>{let segments=[],segment=[];rows.forEach((r,i)=>{if(r[key]==null){if(segment.length)segments.push(segment);segment=[]}else segment.push([x(i),y(r[key])])});if(segment.length)segments.push(segment);return segments.map(points=>`<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="2.2" stroke-linejoin="round"/>`).join('')+rows.map((r,i)=>r[key]==null?'':`<circle cx="${x(i)}" cy="${y(r[key])}" r="${rows.length===1?4:3}" fill="${color}" class="chart-point"><title>${esc(r.date)} · ${esc(key==='revenue'?'销售额':key==='stock'?'期末库存':key==='sales'?'销量':key==='demand'?'预计销量':'入库量')}：${num(r[key])} ${esc(unit)}</title></circle>`).join('')}).join('')}${ticks.map(i=>`<text x="${x(i)}" y="240" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}" fill="#728479" font-size="11">${esc(rows[i]?.date)}</text>`).join('')}</svg>`
}
function bars(rows,key='sales'){const valid=rows.filter(p=>p[key]!=null),max=Math.max(1,...valid.map(p=>p[key]));return valid.map(p=>`<div class="bar-row"><span>${esc(p.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${100*p[key]/max}%"></div></div><b>${num(p[key])}</b></div>`).join('')+rows.filter(p=>p[key]==null).map(p=>`<div class="bar-row"><span>${esc(p.name)}</span><span class="muted">数据不全</span><span>—</span></div>`).join('')||'<p>暂无完整数据</p>'}
function categoryDonut(rows){
 if(rows.some(r=>r.revenue==null))return '<p class="note">部分品类数据不全，暂不展示销售额占比。</p>';
 const sorted=[...rows].sort((a,b)=>b.revenue-a.revenue),total=sorted.reduce((n,r)=>n+r.revenue,0);
 if(!total)return '<p class="note">当前期间暂无销售额。</p>';
 const colors=['#267957','#65a98d','#c6a356','#688eaa','#b3889c','#8f9b58'];let offset=0;
 const arcs=sorted.map((r,i)=>{const percent=r.revenue/total*100;const arc=`<circle cx="100" cy="100" r="76" pathLength="100" fill="none" stroke="${colors[i%colors.length]}" stroke-width="27" stroke-dasharray="${percent} ${100-percent}" stroke-dashoffset="${-offset}" transform="rotate(-90 100 100)"><title>${esc(r.name)}：${num(r.revenue)} 元，占 ${num(percent)}%</title></circle>`;offset+=percent;return arc}).join('');
 return `<div class="donut-layout"><div class="donut-visual"><svg viewBox="0 0 200 200" role="img" aria-label="品类销售额占比">${arcs}</svg><div class="donut-center"><span>销售总额（元）</span><strong>${num(total)}</strong></div></div><div class="donut-legend">${sorted.map((r,i)=>`<div class="donut-item"><span class="donut-dot" style="background:${colors[i%colors.length]}"></span><span class="donut-name">${esc(r.name)}<small>${num(r.revenue)} 元</small></span><b>${num(r.revenue/total*100)}%</b></div>`).join('')}</div></div>`
}
function analysisMetrics(s){
 const items=[['销售额',s.total_revenue,'total_revenue','元'],['销量',s.total_sales,'total_sales','件'],['日均销售额',s.daily_revenue,'daily_revenue','元'],['库存周转',s.turnover,'turnover','次'],['当前需补货',workspace.state.forecast_revision===workspace.state.revision?s.products.filter(p=>workspace.state.forecasts[p.sku]?.status==='ready'&&workspace.state.forecasts[p.sku].quantity>0).length:null,null,'个商品']];
 return `<div class="metrics analytics-metrics">${items.map(([title,value,key,unit])=>{const c=key?s.comparison.changes[key]:null;let label='',direction='';if(c){const amount=key==='turnover'?c.delta:c.percent;direction=amount>0?'up':amount<0?'down':'';label=amount==null?(c.reason||'暂无对比'): `${amount>0?'↑':amount<0?'↓':'→'} ${num(Math.abs(amount))}${key==='turnover'?' 次':'%'}`;}return `<div class="metric"><span>${title}</span><strong>${num(value)}<small> ${unit}</small></strong><div class="metric-change ${direction}">${esc(label)}</div></div>`}).join('')}</div><p class="note metrics-note">注：${s.start} 至 ${s.end} · 对比 ${s.comparison.start} 至 ${s.comparison.end}（前一个等长周期）。库存周转为销量 ÷ 日均库存，按数量统计。</p>`
}
function analytics(){const s=workspace.statistics, products=s.products, valid=products.filter(p=>p.turnover!=null);const insight=workspace.state.insight,matching=insight&&insight.start===s.start&&insight.end===s.end&&(insight.category||'')===category;return analysisMetrics(s)+(products.some(p=>p.missing)?'<div class="warning">部分商品销售记录缺失，汇总数字暂不显示。可在销售明细中补全；排行仅包含记录完整的商品。</div>':'')+`<div class="grid">`+panel('销售额趋势',`<div class="panel-body">${chart(s.trend,[['revenue','#318164']],'元')}</div>`)+panel('品类销售额（元）',`<div class="panel-body">${categoryDonut(s.categories)}</div>`)+`</div><div class="grid">`+panel('库存趋势',`<div class="panel-body">${chart(s.trend,[['stock','#318164']])}</div>`)+panel('入库与销售消耗',`<div class="panel-body"><div class="legend"><b>━ 销售</b><span>━ 入库</span></div>${chart(s.trend,[['sales','#318164'],['received','#c0a35b']])}</div>`)+`</div><div class="rank">`+[['销售额 TOP 10',products.filter(p=>p.revenue!=null).sort((a,b)=>b.revenue-a.revenue),'revenue'],['周转最快 TOP 10',[...valid].sort((a,b)=>b.turnover-a.turnover),'turnover'],['周转最慢 TOP 10',[...valid].sort((a,b)=>a.turnover-b.turnover),'turnover']].map(([title,rows,key])=>panel(title,`<div class="panel-body">${rows.slice(0,10).map((p,i)=>`<div class="bar-row"><span>${i+1}. ${esc(p.name)}</span><b>${num(p[key])}${key==='turnover'?'×':' 元'}</b></div>`).join('')||'暂无完整库存历史'}</div>`)).join('')+`</div><p class="note">期间周转次数＝商品期间销量 ÷ 同期日均库存；平均库存为零或历史不完整时不计算。图表断点表示数据不全。</p>`+insightPanel()}
function settings(){const v=workspace?.state.parameters||{lead_days:7,service:.95};return panel('1 · 准备数据',`<div class="panel-body"><p>${dataset?(dataset.synthetic?'已加载示例数据':'已加载本地数据'):'先导入本地数据，或使用已准备好的示例数据。'}</p><div class="toolbar" style="margin-top:16px">${button('导入本地数据','import','','primary')}${button('加载示例数据','sample')}</div><p class="note">导入窗口提供商品目录和每日销售台账模板。重新导入会建立独立工作区。</p></div>`)+`<form id="setup-form">`+panel('2 · 确认备货规则',`<div class="panel-body"><div class="form-grid"><div><label>生产提前期（天）</label><input name="lead_days" type="number" min="1" max="30" value="${v.lead_days}" required><p class="note">从提出需求到预计成品可以入库的时间。</p></div><div><label>目标服务水平（%）</label><input name="service_percent" type="number" min="50" max="99" step="1" value="${Math.round(v.service*100)}" required><p class="note">影响安全库存余量。水平越高，通常准备的库存越多，不代表实际服务保证。</p></div></div><p class="note">检查周期固定为每天，无需填写。目标库存覆盖生产提前期加 1 天的需求，并保留安全库存。</p></div>`)+`<div class="form-actions"><button class="primary" type="submit" ${!dataset?'disabled':''}>${workspace?.state.setup_complete?'保存设置并更新计算':'完成设置并开始计算'}</button></div></form>`}

function render(){page=location.hash.slice(1)||'overview';if(!pages[page])page='overview';$('#title').textContent=pages[page][0];$('#subtitle').textContent=pages[page][1];$('#crumb').textContent='工作区 / '+pages[page][0];$('#nav').innerHTML=Object.entries(pages).filter(([k])=>k!=='settings').map(([k,[t,,icon]])=>`<a href="#${k}" class="${page===k?'active':''}"><span>${icon}</span>${t}</a>`).join('');$('#actions').innerHTML=dataset&&page==='planning'?button(workspace.state.setup_complete?'重新计算':'完成首次设置',workspace.state.setup_complete?'forecast-all':'setup'):button('导入数据','import');if(!dataset&&page!=='settings'){$('#content').innerHTML=empty();return}if(dataset&&['inventory','sales'].includes(page))$('#actions').innerHTML=button('导出 CSV','export-details')+button('导入数据','import');const filters=dataset&&['inventory','sales','analytics','planning'].includes(page)?`<div class="toolbar">${page==='analytics'?`<label>开始日期 <input type="date" id="analysis-start" value="${analysisStart||workspace.statistics.start}"></label><label>结束日期 <input type="date" id="analysis-end" max="${new Date(new Date(dataset.as_of+'T00:00:00Z').getTime()-86400000).toISOString().slice(0,10)}" value="${analysisEnd||workspace.statistics.end}"></label>${button('应用日期','apply-range','','primary')}`:''}<select id="days">${page==='analytics'&&analysisStart?'<option value="custom" selected>自定义范围</option>':''}${[7,30,90].map(v=>`<option ${days===v&&!(page==='analytics'&&analysisStart)?'selected':''} value="${v}">近 ${v} 天</option>`).join('')}</select>${page==='analytics'?`<select id="category"><option value="">全部品类</option>${[...new Set(Object.values(workspace.state.product_settings).map(p=>p.category).concat('未分类'))].map(c=>`<option ${category===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`:`<input id="search" placeholder="搜索商品名称或 SKU" value="${esc(search)}">`}</div>`:'';$('#content').innerHTML=filters+(workspace?.state.calculation?.status==='running'?`<div class="warning">自动计算中 ${workspace.state.calculation.done} / ${workspace.state.calculation.total}，可以继续浏览，已有结果保留展示。</div>`:'')+({overview,planning,requests,inventory,sales,analytics,settings}[page])()}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function importDialog(){modal('导入销售与库存数据',`<form id="import-form"><p>上传 UTF-8 CSV，先下载模板，按字段填写后上传。</p><div class="toolbar"><a class="button" href="/template/products" download>下载商品模板</a><a class="button" href="/template/sales" download>下载销售台账模板</a></div><p class="note">当日入库数量填写在 received_units 字段，没有入库填 0。</p><label>商品目录</label><input name="products" type="file" accept=".csv" required><label>每日销售台账</label><input name="sales" type="file" accept=".csv" required><label>数据截至日（历史不包含当天）</label><input name="as_of" type="date" value="${dataset?.as_of||new Date().toISOString().slice(0,10)}" required><p class="note">导入建立新工作区，原单据不会自动迁移。库存需与台账衔接。</p><div class="form-actions"><button class="primary">校验并导入</button></div></form>`)}
async function forecast(sku){const f=workspace.state.forecasts[sku];if(!f){toast(workspace.state.setup_complete?'正在后台计算，请稍候':'请先完成首次设置');if(!workspace.state.setup_complete)await setupDialog();return;}const p=workspace.statistics.products.find(p=>p.sku===sku);if(f.status!=='ready'){modal('暂未生成备货建议 · '+(p?.name||sku),blockedExplanation(f,sku));return}const pending=workspace.state.requests.find(o=>['draft','pending'].includes(o.status)&&o.lines.some(l=>l.sku===sku));modal('备货方案 · '+p.name,(f.revision!==workspace.state.revision?'<div class="warning">数据已更新，以下为上次结果。重新计算完成后才可据此生成需求单。</div>':'')+metrics([['目标库存',f.target_stock,'覆盖整个预测期'],['安全库存',f.safety,'历史误差校准'],['计入的待入库',f.incoming_counted,'在预测期内承诺到达'],['建议新增',f.quantity,'尚未自动生成单据']])+`${f.first_shortage?`<div class="warning">现有安排下，预计 ${esc(f.first_shortage)} 出现缺口。正常生产预计 ${esc(f.due)} 入库，请核对是否来得及。</div>`:''}${f.overdue_incoming?`<div class="warning">${f.overdue_incoming} 件确认入库已延期，未计作可及时到货。</div>`:''}<div class="forecast-chart"><div class="legend"><b>━ 不新增补货时的库存</b><span>━ 预计销量</span></div>${chart(f.daily,[['stock','#318164'],['demand','#c0a35b']])}<p class="note">库存低于零的部分表示预计缺口。</p></div>${f.revision!==workspace.state.revision?'<p>方案更新中…</p>':pending?`<div class="warning">已有待处理需求 ${esc(pending.id)}，请先处理原单。</div>`:`<form id="create-form" data-sku="${esc(sku)}"><div class="form-grid"><div><label>申请数量</label><input name="quantity" type="number" min="1" value="${f.quantity||1}" required></div><div><label>期望入库日期</label><input name="due" type="date" min="${dataset.as_of}" value="${f.due}" required></div></div><div class="form-actions"><button class="primary">生成补货需求单草稿</button></div></form>`}<details><summary>预测逐日明细</summary>${table(['日期','预计销量','不新增补货时的库存'],f.daily.map(r=>`<tr><td>${r.date}</td><td>${num(r.demand)}</td><td>${num(r.stock)}</td></tr>`))}</details>`)}
function orderDialog(id){const o=workspace.state.requests.find(o=>o.id===id);modal(id+' · '+status[o.status],table(['商品','需求数量','确认数量','已入库','期望 / 承诺日期'],o.lines.map(l=>`<tr><td>${esc(dataset.products.find(p=>p.sku===l.sku)?.name||l.sku)}</td><td>${l.quantity}</td><td>${l.confirmed}</td><td>${l.received}</td><td>${l.due}<br>${l.confirmed_due||'—'}</td></tr>`))+o.lines.filter(l=>l.confirmed_due&&(l.confirmed<l.quantity||l.confirmed_due>l.due)).map(l=>`<div class="warning">${esc(l.sku)}：确认数量或交期与原需求不一致，请核对备货缺口。</div>`).join('')+`<div class="form-actions">${o.status==='draft'?button('确认需求','submit-order',`data-id="${id}"`,'primary'):o.status==='pending'?button('录入生产反馈','feedback',`data-id="${id}"`,'primary'):['confirmed','partial'].includes(o.status)?button('登记入库','receive',`data-id="${id}"`,'primary'):''}${!['completed','cancelled'].includes(o.status)?button('取消剩余需求','cancel-order',`data-id="${id}"`):''}</div>`)}
function feedbackDialog(id,receive=false){const o=workspace.state.requests.find(o=>o.id===id),lines=o.lines.filter(l=>!receive||l.received<l.confirmed);modal(receive?'登记入库':'录入生产反馈',`<form id="feedback-form" data-id="${id}" data-kind="${receive?'receive':'feedback'}"><p>${receive?'本次按工作区库存截至日登记，可分批入库。':'填写线下沟通后生产部门承诺的数量和日期。'}</p>${lines.map(l=>`<section class="feedback-product"><h3>${esc(dataset.products.find(p=>p.sku===l.sku)?.name||l.sku)}</h3><p class="feedback-reference">SKU ${esc(l.sku)} · 原需求 ${num(l.quantity)} 件 · 期望入库 ${esc(l.due)}</p><div class="feedback-fields" data-line="${esc(l.sku)}"><div><label>${receive?'本次入库':'生产确认'}数量</label><input name="qty-${esc(l.sku)}" type="number" min="${receive?0:1}" ${receive?`max="${l.confirmed-l.received}"`:''} required ${receive?'value="0"':''}></div><div><label>${receive?'入库日期':'承诺入库日期'}</label><input name="due-${esc(l.sku)}" type="date" min="${dataset.as_of}" ${receive?`value="${dataset.as_of}" readonly`:''} required></div>${!receive?button('与原需求一致','fill-original',`data-id="${id}" data-sku="${esc(l.sku)}"`,'small'):''}</div></section>`).join('')}<label>备注</label><textarea name="note" rows="2" style="width:100%"></textarea><div class="form-actions"><button class="primary">保存${receive?'入库':'反馈'}</button></div></form>`)}
async function productDialog(sku){const p=workspace.statistics.products.find(p=>p.sku===sku),values=workspace.state.product_settings[sku]||{};modal(p.name,`<form id="product-form" data-sku="${esc(sku)}"><p>SKU ${esc(sku)} · 现货 ${num(p.stock)} · 已确认待入库 ${num(p.incoming)}</p><label>商品品类</label><input name="category" value="${esc(values.category||'未分类')}" required maxlength="40"><label>商品生产提前期（留空使用全局默认）</label><input name="lead_days" type="number" min="1" max="30" value="${values.lead_days||''}"><div class="form-actions"><button class="primary">保存商品参数</button></div></form>`)}
async function repairDialog(sku){const d=await api(`/detail/${dataset.dataset_id}/${encodeURIComponent(sku)}`);if(!d.missing_dates.length){toast('当前没有缺失日期');return}modal('补全销售记录',`<form id="repair-form" data-sku="${esc(sku)}"><p>按日期顺序补录。期初库存 ${num(d.repair_opening)}，期末＝期初＋入库－销量。</p><label>缺失日期</label><input name="day" value="${d.missing_dates[0]}" readonly><label>当日销量</label><input name="units" type="number" min="0" required><label>当日售价</label><input name="selling_price" type="number" step=".01" min=".01" required><label>当日入库数量（没有则填 0）</label><input name="received_units" type="number" min="0" value="0" required><div class="form-actions"><button class="primary">保存并重算库存</button></div></form>`)}
$('#close-modal').onclick=()=>$('#modal').close();
window.addEventListener('hashchange',async()=>{search=stockJump||'';stockJump=null;category='';if(!['analytics','sales'].includes(location.hash.slice(1)))days=30;await refresh();render()});
document.addEventListener('change',async e=>{try{if(e.target.id==='days'){if(e.target.value==='custom')return;days=Number(e.target.value);if(page==='analytics'){analysisStart='';analysisEnd=''}await refresh()}if(e.target.id==='category'){category=e.target.value;await refresh()}if(e.target.id==='search'){search=e.target.value;render()}}catch(err){toast(err.message)}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,sku=b.dataset.sku,id=b.dataset.id;b.disabled=true;try{if(a==='auth-mode')showAuth(b.dataset.mode);else if(a==='logout'){await fetch('/auth/logout',{method:'POST'});dataset=null;workspace=null;showAuth('login')}else if(a==='apply-range'){const start=$('#analysis-start').value,end=$('#analysis-end').value;if(!start||!end||start>end||end>=dataset.as_of)throw Error('请选择有效日期范围，结束日期须早于数据截至日');analysisStart=start;analysisEnd=end;await refresh()}else if(a==='export-details')exportDetails();else if(a==='import')importDialog();else if(a==='sample'){if(dataset&&!confirm('加载示例将切换至新的示例工作区，是否继续？'))return;dataset=await api('/sample',{});category='';await refresh()}else if(a==='stock-jump'){stockJump=sku;tab='current';location.hash='inventory'}else if(a==='tab'){tab=b.dataset.tab;render()}else if(a==='forecast')await forecast(sku);else if(a==='setup')await setupDialog();else if(a==='forecast-all'){await api(path('/start'),workspace.state.parameters);await refresh();toast('已开始后台计算')}else if(a==='order')orderDialog(id);else if(a==='feedback')feedbackDialog(id);else if(a==='receive')feedbackDialog(id,true);else if(a==='submit-order'||a==='cancel-order'){if(a==='cancel-order'&&!confirm('取消尚未完成的需求？已发生的入库将保留。'))return;await api(path('/requests/'+id),{action:a==='submit-order'?'submit':'cancel'});await refresh();orderDialog(id)}else if(a==='fill-original'){const o=workspace.state.requests.find(o=>o.id===id);for(const l of o.lines.filter(l=>l.sku===sku)){document.getElementsByName('qty-'+l.sku)[0].value=l.quantity;document.getElementsByName('due-'+l.sku)[0].value=l.due}}else if(a==='product')productDialog(sku);else if(a==='repair')await repairDialog(sku);else if(a==='goto-sales'){$('#modal').close();location.hash='sales'}else if(a==='insight'){await runInsight(true)}}catch(err){toast(err.message)}finally{b.disabled=false;if(a==='insight')b.textContent='重试';if(a==='forecast-all')b.textContent='评估全部商品'}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),b=form.querySelector('button[type=submit],button.primary');if(b)b.disabled=true;try{if(form.id==='auth-form'){const r=await fetch('/auth/'+form.dataset.mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});if(!r.ok){const out=await r.json();showAuth(form.dataset.mode,out.detail||'操作失败');return}location.reload();return}else if(form.id==='setup-form'){await api(path('/start'),{lead_days:Number(fd.get('lead_days')),service:Number(fd.get('service_percent'))/100});location.hash='planning'}else if(form.id==='import-form'){dataset=await api('/upload',{products_csv:await fd.get('products').text(),sales_csv:await fd.get('sales').text(),as_of:fd.get('as_of')});category=''}else if(form.id==='settings-form'){await api(path('/settings'),{lead_days:Number(fd.get('lead_days')),service:Number(fd.get('service'))});}else if(form.id==='product-form'){await api(path('/product/'+encodeURIComponent(form.dataset.sku)),{category:fd.get('category'),lead_days:fd.get('lead_days')?Number(fd.get('lead_days')):null})}else if(form.id==='create-form'){await api(path('/requests'),{token:crypto.randomUUID(),lines:[{sku:form.dataset.sku,quantity:Number(fd.get('quantity')),due:fd.get('due')}]})}else if(form.id==='feedback-form'){const receive=form.dataset.kind==='receive';let lines=[...form.querySelectorAll('[data-line]')].map(el=>({sku:el.dataset.line,quantity:Number(fd.get('qty-'+el.dataset.line)),due:fd.get('due-'+el.dataset.line)}));if(receive)lines=lines.filter(l=>l.quantity>0);await api(path('/requests/'+form.dataset.id),{action:form.dataset.kind,lines,note:fd.get('note'),token:form.dataset.token||(form.dataset.token=crypto.randomUUID())})}else if(form.id==='repair-form'){const received=Number(fd.get('received_units'));dataset=await api('/repair',{dataset_id:dataset.dataset_id,sku:form.dataset.sku,day:fd.get('day'),units:Number(fd.get('units')),selling_price:fd.get('selling_price'),has_receipt:received>0,received_units:received})}else return;$('#modal').close();if(form.id==='create-form'){location.hash='requests';toast('补货需求单草稿已生成')}else{await refresh();toast('已保存')}}catch(err){if(form.id==='auth-form')showAuth(form.dataset.mode,err.message);else toast(err.message)}finally{if(b)b.disabled=false}});
(async()=>{try{const meResponse=await fetch('/auth/me');if(meResponse.status===401){showAuth('login');return}if(!meResponse.ok)throw Error('登录服务暂不可用');showApp(await meResponse.json());const config=await api('/config');modelConfigured=!!config.chat_configured;const data=await api('/workspace');dataset=data.dataset;if(dataset)await refresh();else {location.hash='settings';render()}loaded=true}catch(err){document.body.className='';render();toast('工作区载入失败：'+err.message)}})();

async function setupDialog(){if(location.hash!=='#settings')location.hash='settings';else render()}

function shortHistory(result){return /^保护期 .*需要至少 .*连续记录/.test(result?.reason||'')}
function blockedExplanation(result,sku){
 if(!shortHistory(result))return `<div class="warning">暂未生成自动备货建议</div><p>${esc(result.reason||'本次计算未完成，请核对数据后重试。')}</p><p class="note">这不代表无需补货，也没有生成可用的补货数量。</p>${button('查看销售明细','goto-sales')}`;
 const match=(result.reason||'').match(/当前 (\d+) 天/),count=match?match[1]:dataset.products.find(p=>p.sku===sku)?.history_rows;
 return `<div class="warning"><strong>销售历史较短，暂未生成自动备货建议</strong></div><p>该商品目前有 ${esc(count??'较少')} 天销售记录，尚不足以支持当前算法完成预测验证和安全库存估计。</p><p>这不代表商品没有需求，也不代表无需补货。库存和已有销量仍可正常查看。</p><p class="note">如果有更早的销售记录，可以导入更完整的历史；如果是刚开始销售的商品，可先结合实际销售人工判断备货，继续积累数据。</p><div class="toolbar">${button('查看销售明细','goto-sales')}${button('导入更多历史','import')}</div><details><summary>查看计算要求</summary><p class="note">${esc(result.reason)} 此门槛来自当前算法的历史验证与校准设置，并非所有预测方法的通用要求。</p></details>`
}
